apiVersion: v1
kind: Service
metadata:
  name: saferide-api
  labels:
    app: saferide
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: saferide-api