apiVersion: v1
kind: Service
metadata:
  name: saferide-frontend
  labels:
    app: saferide-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: saferide-frontend