apiVersion: apps/v1
kind: Deployment
metadata:
  name: saferide-frontend
  labels:
    app: saferide
spec:
  replicas: 3
  selector:
    matchLabels:
      app: saferide
  template:
    metadata:
      labels:
        app: saferide
    spec:
      containers:
      - name: frontend
        image: saferide-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://saferide-api:5000/api"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
      - name: regcred