name: Deploy to Ultra-Cheap Azure Container

on:
  push:
    branches: [ main ]
    paths: 
      - 'SafeRide/backend/**'
  workflow_dispatch:

jobs:
  deploy-ultra-cheap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and Create Docker Image
      run: |
        cd SafeRide/backend/src/SafeRide.Api
        
        # Create optimized Dockerfile for container instances
        cat > Dockerfile << 'EOF'
        FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS base
        WORKDIR /app
        EXPOSE 80
        
        FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build
        WORKDIR /src
        COPY ["SafeRide.Api.csproj", "."]
        COPY ["../SafeRide.Core/SafeRide.Core.csproj", "../SafeRide.Core/"]
        COPY ["../SafeRide.Infrastructure/SafeRide.Infrastructure.csproj", "../SafeRide.Infrastructure/"]
        RUN dotnet restore "SafeRide.Api.csproj"
        COPY . .
        COPY ../SafeRide.Core ../SafeRide.Core
        COPY ../SafeRide.Infrastructure ../SafeRide.Infrastructure
        RUN dotnet publish "SafeRide.Api.csproj" -c Release -o /app/publish --no-restore
        
        FROM base AS final
        WORKDIR /app
        COPY --from=publish /app/publish .
        ENTRYPOINT ["dotnet", "SafeRide.Api.dll"]
        EOF
        
        # Build image locally (no registry needed for simplicity)
        docker build -t saferide-api .
        
        # Save image as tar for deployment
        docker save saferide-api > saferide-api.tar
    
    - name: Update Container Instance
      run: |
        # For now, just restart the existing container
        # In production, you'd push to a container registry and update
        az container restart \
          --resource-group saferide-free-rg \
          --name saferide-api
        
        echo "Container restarted with updated code"
        
        # Get container URL
        FQDN=$(az container show \
          --resource-group saferide-free-rg \
          --name saferide-api \
          --query "ipAddress.fqdn" \
          --output tsv)
        
        echo "Container URL: http://$FQDN"
