name: Deploy Backend to Australia Southeast

on:
  push:
    branches: [ main ]
    paths: 
      - 'SafeRide/backend/**'
  workflow_dispatch:

jobs:
  deploy-backend-australia:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_AU }}
    
    - name: Build and Deploy
      run: |
        cd SafeRide/backend/src/SafeRide.Api
        
        # Restore and build
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish --configuration Release --output ./publish
        
        # Deploy to Azure Web App (Australia Southeast)
        az webapp deployment source config-zip \
          --resource-group saferide-au-rg \
          --name ${{ vars.AZURE_WEBAPP_NAME_AU }} \
          --src ./publish.zip
    
    - name: Create deployment package
      run: |
        cd SafeRide/backend/src/SafeRide.Api/publish
        zip -r ../publish.zip .
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME_AU }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_AU }}
        package: SafeRide/backend/src/SafeRide.Api/publish
